// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

type Movie struct {
	ID         int64
	CreatedAt  string
	UpdatedAt  string
	Title      string
	TmdbID     int64
	TmdbUrl    string
	PosterPath string
	Status     string
}

type User struct {
	ID             int64
	CreatedAt      string
	UpdatedAt      string
	JellyfinUserID string
	Username       string
	IsAdmin        int64
}

type Vote struct {
	ID        int64
	CreatedAt int64
	UpdatedAt int64
	UserID    int64
	MovieID   int64
	VoteCount int64
}
