// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Movie struct {
	ID         int64
	CreatedAt  string
	UpdatedAt  string
	Title      string
	TmdbUrl    string
	PosterPath string
	Status     string
}

type User struct {
	ID        int64
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
	Username  sql.NullString
}

type Vote struct {
	ID        int64
	CreatedAt int64
	UserID    int64
	MovieID   int64
}
