// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: movies.sql

package database

import (
	"context"
)

const getMovies = `-- name: GetMovies :many
SELECT id, title, description, url, poster_url, status FROM movies
`

type GetMoviesRow struct {
	ID          int64
	Title       string
	Description string
	Url         string
	PosterUrl   string
	Status      string
}

func (q *Queries) GetMovies(ctx context.Context) ([]GetMoviesRow, error) {
	rows, err := q.db.QueryContext(ctx, getMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMoviesRow
	for rows.Next() {
		var i GetMoviesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.PosterUrl,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMovie = `-- name: InsertMovie :one
INSERT INTO movies (id, created_at, updated_at, title, description, url, poster_url, status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, created_at, updated_at, title, description, url, poster_url, status
`

type InsertMovieParams struct {
	ID          int64
	CreatedAt   string
	UpdatedAt   string
	Title       string
	Description string
	Url         string
	PosterUrl   string
	Status      string
}

func (q *Queries) InsertMovie(ctx context.Context, arg InsertMovieParams) (Movie, error) {
	row := q.db.QueryRowContext(ctx, insertMovie,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.Description,
		arg.Url,
		arg.PosterUrl,
		arg.Status,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.PosterUrl,
		&i.Status,
	)
	return i, err
}
