// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
)

const addUser = `-- name: AddUser :exec
INSERT INTO users (id, created_at, updated_at, username)
VALUES (?,?,?,?)
`

type AddUserParams struct {
	ID        int64
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
	Username  sql.NullString
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) error {
	_, err := q.db.ExecContext(ctx, addUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Username,
	)
	return err
}
