// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
)

const addUser = `-- name: AddUser :one
INSERT INTO users (created_at, updated_at, jellyfin_user_id, username, is_admin)
VALUES (?,?,?,?,?)
RETURNING id, created_at, updated_at, jellyfin_user_id, username, is_admin
`

type AddUserParams struct {
	CreatedAt      string
	UpdatedAt      string
	JellyfinUserID string
	Username       string
	IsAdmin        int64
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, addUser,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.JellyfinUserID,
		arg.Username,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JellyfinUserID,
		&i.Username,
		&i.IsAdmin,
	)
	return i, err
}

const getUserByJellyID = `-- name: GetUserByJellyID :one
SELECT id, created_at, updated_at, jellyfin_user_id, username, is_admin FROM users
WHERE jellyfin_user_id = ?
`

func (q *Queries) GetUserByJellyID(ctx context.Context, jellyfinUserID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByJellyID, jellyfinUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JellyfinUserID,
		&i.Username,
		&i.IsAdmin,
	)
	return i, err
}
