// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: votes.sql

package database

import (
	"context"
	"database/sql"
)

const checkMovieVotes = `-- name: CheckMovieVotes :one
SELECT v.id, v.vote_count
FROM votes v
WHERE v.movie_id = ? AND v.user_id = ?
`

type CheckMovieVotesParams struct {
	MovieID int64
	UserID  int64
}

type CheckMovieVotesRow struct {
	ID        int64
	VoteCount int64
}

func (q *Queries) CheckMovieVotes(ctx context.Context, arg CheckMovieVotesParams) (CheckMovieVotesRow, error) {
	row := q.db.QueryRowContext(ctx, checkMovieVotes, arg.MovieID, arg.UserID)
	var i CheckMovieVotesRow
	err := row.Scan(&i.ID, &i.VoteCount)
	return i, err
}

const createVote = `-- name: CreateVote :one
INSERT INTO votes (created_at, updated_at, user_id, movie_id, vote_count)
VALUES (?, ?, ?, ?, ?)
RETURNING id, created_at, updated_at, user_id, movie_id, vote_count
`

type CreateVoteParams struct {
	CreatedAt int64
	UpdatedAt int64
	UserID    int64
	MovieID   int64
	VoteCount int64
}

func (q *Queries) CreateVote(ctx context.Context, arg CreateVoteParams) (Vote, error) {
	row := q.db.QueryRowContext(ctx, createVote,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.MovieID,
		arg.VoteCount,
	)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.MovieID,
		&i.VoteCount,
	)
	return i, err
}

const getMoviesByUserVotes = `-- name: GetMoviesByUserVotes :many
SELECT m.id, m.created_at, m.updated_at, m.title, m.tmdb_id, m.tmdb_url, m.poster_path, m.status, v.vote_count
FROM movies m
INNER JOIN votes v on m.id = v.movie_id
WHERE v.user_id = ?
`

type GetMoviesByUserVotesRow struct {
	ID         int64
	CreatedAt  string
	UpdatedAt  string
	Title      string
	TmdbID     int64
	TmdbUrl    string
	PosterPath string
	Status     string
	VoteCount  int64
}

func (q *Queries) GetMoviesByUserVotes(ctx context.Context, userID int64) ([]GetMoviesByUserVotesRow, error) {
	rows, err := q.db.QueryContext(ctx, getMoviesByUserVotes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMoviesByUserVotesRow
	for rows.Next() {
		var i GetMoviesByUserVotesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.TmdbID,
			&i.TmdbUrl,
			&i.PosterPath,
			&i.Status,
			&i.VoteCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByMoveisVoted = `-- name: GetUsersByMoveisVoted :many
SELECT u.username
FROM users u
INNER JOIN votes v on u.id = v.user_id
WHERE v.movie_id = ?
`

func (q *Queries) GetUsersByMoveisVoted(ctx context.Context, movieID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUsersByMoveisVoted, movieID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var username string
		if err := rows.Scan(&username); err != nil {
			return nil, err
		}
		items = append(items, username)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVotesCountPerUser = `-- name: GetVotesCountPerUser :one
SELECT SUM(vote_count) FROM votes
WHERE user_id = ?
`

func (q *Queries) GetVotesCountPerUser(ctx context.Context, userID int64) (sql.NullFloat64, error) {
	row := q.db.QueryRowContext(ctx, getVotesCountPerUser, userID)
	var sum sql.NullFloat64
	err := row.Scan(&sum)
	return sum, err
}

const updateVoteCount = `-- name: UpdateVoteCount :exec
UPDATE votes
SET updated_at= ?, vote_count = ?
WHERE id = ?
`

type UpdateVoteCountParams struct {
	UpdatedAt int64
	VoteCount int64
	ID        int64
}

func (q *Queries) UpdateVoteCount(ctx context.Context, arg UpdateVoteCountParams) error {
	_, err := q.db.ExecContext(ctx, updateVoteCount, arg.UpdatedAt, arg.VoteCount, arg.ID)
	return err
}
